### ISSUE TITLE
Does not allow getters.

### ISSUE THREAD

**Issue by DylanVann** [TristonJ/eslint-plugin-prefer-arrow#10]
This is considered an arrow:

```js
const myObject = {
    get myVal() {
      return something()
    },
}
```

The fix will convert it to:

```js
const myObject = {
    get myVal: () => something(),
}
```

Which is not valid.

**Comment by TristonJ** [comment]
Thanks for the report! This has been fixed in https://github.com/TristonJ/eslint-plugin-prefer-arrow/commit/384bc9db8452e52a8613b2675f6706184b976e5b and pushed to npm as a patch.

**Comment by DylanVann** [comment]
Awesome, thank you @TristonJ !
