### ISSUE TITLE
autofix async function broken

### ISSUE THREAD

**Issue by omegalink12** [TristonJ/eslint-plugin-prefer-arrow#12]
Trying to autofix an async function doesn't pick up the async modifier.

```js
async function x(){
  return 1
}
```

gets autofixed to

```js
async const x = ()=> 1;
```

**Comment by TristonJ** [comment]
Thank you for the report! This has been fixed in 304160a and published to npm. If you are using the `singleReturnOnly` option, your example should get autofixed to ```js
const x = async () => 1;
```
