### ISSUE TITLE
Allow standalone function declarations

### ISSUE THREAD

**Issue by astorije** [TristonJ/eslint-plugin-prefer-arrow#16]
This plugin is an excellent replacement for [TSLint's `only-arrow-functions`](https://palantir.github.io/tslint/rules/only-arrow-functions/), as even recommended by the [`typescript-eslint` project](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md#typescript-specific).

However, `only-arrow-functions` has the `allow-declarations` option which allows for standalone declarations. In our codebase, we use non-arrow on every top-level function so using this plugin triggers hundreds of violations.

I would love to be able to use this rule to disallow the format above, without having to reformat our codebase. What do you think of an additional `allowDeclarations` option?

In fact, we were/are using the `recommended` preset of `tslint-microsoft-contrib`, [which uses this option](https://github.com/microsoft/tslint-microsoft-contrib/blob/master/tslint.json#L8), so it would make transitioning from TSLint to ESLint even easier :)

**Comment by TristonJ** [comment]
@astorije Thank you for the detailed issue! I've just created a new commit (https://github.com/TristonJ/eslint-plugin-prefer-arrow/commit/2d631d97dff1bce5d671b505f1f11f761985e703) published a new minor version to npm adding a `allowStandaloneDeclarations` option.

The option allows function declarations at the top level, but still warns about declarations inside other "inner" scope. For example, with `allowStandaloneDeclarations` set to true, this would be valid:
```js
function hello() {
  return "world";
}
```

but the following would throw a warning
```js
function hello() {
  // Would warn about the following function
  return function() {
    return "world";
  }
}
```
Please let me know if this addresses your issue, thanks!

**Comment by TristonJ** [comment]
I am going to go ahead and close this issue. If there are bugs or additional requests / thoughts, please open a new issue.
