### ISSUE TITLE
function* expression not being detected

### ISSUE THREAD

**Issue by marekdedic** [TristonJ/eslint-plugin-prefer-arrow#30]
Hi,
I think the expression

```js
var foo = function*() { return yield "bar"; };
```

should be an error with the default settings. However, it is not.

**Comment by dkimmich-onventis** [comment]
It's because you can't use arrow functions with generators, see https://stackoverflow.com/questions/27661306/can-i-use-es6s-arrow-function-syntax-with-generators-arrow-notation.

**Comment by marekdedic** [comment]
Oh, OK, that explains it, thanks :)
