### ISSUE TITLE
prefer-arrow-functions rule autofix breaks for loop condition in function body

### ISSUE THREAD

**Issue by romick101** [TristonJ/eslint-plugin-prefer-arrow#7]
Try adding the following to the invalid section of unit tests: 
`['function withLoop() { return () => { for (i = 0; i < 5; i++) {}}}', 'const withLoop = () => () => { for (i = 0; i < 5; i++) {}};']`
The test will fail because produced code will look like this: 
`const withLoop = () => () => { for (i = 0; i < 5i++) {}};`
The second semicolon is removed which leads to syntax error in the code.

**Comment by TristonJ** [comment]
This should be fixed in https://github.com/TristonJ/eslint-plugin-prefer-arrow/commit/f15d389074cd2efa00824d83391d46b720451840
